-- V1: initial schema for job applications.
-- Column names match Hibernate's default snake_case mapping of the Job entity
-- (dateApplied -> date_applied, hrContact -> hr_contact).
CREATE TABLE jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company      VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL,
    date_applied DATE,
    hr_contact   VARCHAR(255)
);

-- The tab views and pie chart both group/filter by status, so index it.
CREATE INDEX idx_jobs_status ON jobs (status);
