-- V2: add user accounts and make each job belong to a user.

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,           -- BCrypt hash
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);

-- Owner of each job. Nullable so existing rows survive the migration; the
-- data seeder adopts any ownerless jobs into the demo account on startup.
ALTER TABLE jobs ADD COLUMN user_id BIGINT REFERENCES users(id);
CREATE INDEX idx_jobs_user_id ON jobs (user_id);
